In [2]:
import numpy as np

In [3]:
## creating arrays 

arr_1d = np.array([1,2,3,4,5])

print(arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6], [1,2,5,]])

print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [1 2 5]]


In [4]:
np_array = np.array([1,2,3]) # element wise multipllication
print("Array multiplication by scalar", np_array * 2)

Array multiplication by scalar [2 4 6]


In [14]:
import time
start = time.time()

py_list = [i*2 for i in range(1000000)]

print("\n List operation time: ", time.time() - start)


start = time.time()
np_array = np.arange(1000000) * 2

print("\n NUMPY arraay operation time: ", time.time() - start)



 List operation time:  0.05508923530578613

 NUMPY arraay operation time:  0.0018229484558105469


In [30]:
## creating arrays from scratch

zeros = np.zeros((3,4)) # zero matrix

# print(zeros)

ones = np.ones((232,312)) ## identity matrix

# print(ones) 

full_1 = np.full((2,2), 7)
full_2 = np.ones((2,2))*7

# print(full_1)

# print(full_2)


random = np.random.random((2,3)) # values between 0 to 1
print(random)

sequence = np.arange(0,11,2 ) # hahaha

print(sequence)


[[0.52355469 0.76301301 0.34154382]
 [0.6188967  0.78843731 0.67199466]]
[ 0  2  4  6  8 10]


In [40]:
## VECTORS, MATRIX and TENSOR

vector = np.array([1,2,3]) # 1D array matlab ek array

matrix = np.array([[1,2,3], 
                   [4,5,6]]) # two arrays

# print(matrix)

tensor = np.array([[[1,2], [3,4]],
                   [[5,6], [8,9]]]) # multiple arrays dimensions

# print(tensor)
## ARRAY PROPERTIES / TENSOR PROP
print("shape", tensor.shape)
print("dimnesion", tensor.ndim)
print("size", tensor.size) ## total numver of elelments
print("data type", tensor.dtype)


shape (2, 2, 2)
dimnesion 3
size 8
data type int64


In [51]:
## Array reshaping

arr = np.arange(12)
print(" Origianl array\n",arr)

reshaped = arr.reshape((3,4))
print(" reshaped aray\n",reshaped)

flattened = reshaped.flatten()
print("\n Flattened array", flattened)

## wow raveled
# returns view, instead of copy
# means this is changing origianl array right, 
raveled = reshaped.ravel()
print("\n raveled array", raveled)

# Transpose  (12th matrix)
transpose  = reshaped.T

print(transpose)


 Origianl array
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
 reshaped aray
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
