### Numpy Array operations

In [1]:
import numpy as np

In [15]:
## indexing and slicing

# 1 D ARRAY
arr = np.arange(0,10)
# print(arr)
# print("Basic Slicing", arr[2:7])
# print("with step", arr[1:8:2])
# print("Negative indexing", arr[-3])


# 2 D ARRAY 
arr_2d = np.array([[1,2,3,],
                [4,5,6],
                [7,8,9]])

print("Specific element", arr_2d[1, 2]) # first row third column 
print("entire row", arr_2d[2, :]) # third row
print("entire column", arr_2d[:, 2]) # third column


Specific element 6
entire row [7 8 9]
entire column [3 6 9]


In [ ]:
## SORTING

unsorted = np.array([3,1,1,4,6,6,2,3,6,3,6,2,7,8,6])
print("Sorted Array: ", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1], [1,2], [2, 3]])
print("sorted 2d array by column", np.sort(arr_2d_unsorted, axis=0)) # top to bottom ## use axis = 1 for sorting in row

Sorted Array:  [1 1 2 2 3 3 3 4 6 6 6 6 6 7 8]
sorted 2d array by column [[1 1]
 [2 2]
 [3 3]]


In [23]:

## filters
numbers = np.arange(1,11)
print(numbers)

even_number = numbers[numbers % 2 == 0] # if divided by 2 and return zero then include that otherwise exlcude
print(even_number)

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]


In [27]:
## filter with mask
# expression that evaluates is actually a mask
mask = numbers > 5
print("WTF is mask", mask) ## DAMNNN

print("Numbers greater than 5 ", numbers[mask]) 

WTF is mask [False False False False False  True  True  True  True  True]
Numbers greater than 5  [ 6  7  8  9 10]


In [35]:
## FANCY indexing vs np.where()

## DAMNNNNNNN

indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers  > 5) ## it is a index matrix only used for masking 
print("NP WHERE", numbers[where_result])

[1 3 5]
NP WHERE [ 6  7  8  9 10]


In [39]:
condition_array = np.where(numbers > 5, numbers*4, numbers) ## iska matlab hei,, jo numbers greater than 5 hein, unko 4 se multiple krde behenchod, aur baaki ka kuch mat k..  this is basically 'x' or 'y' if or else type cheez
print(condition_array) ## basically returns indices of the given array jahan

[ 1  2  3  4  5 24 28 32 36 40]


In [41]:
# ADDING AND REMOVING DATA

arr1 = np.arange(1,4)
arr2 = np.arange(4,6)

combined = np.concatenate((arr1, arr2))

print(combined)


[1 2 3 4 5]


In [51]:
## array compatibility

a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatibility shapes", a.shape == b.shape)



Compatibility shapes True


In [65]:
original =  np.array([[1,2,],
                      [3,4,]])

new_row = np.array([[5,6]])

with_new_row = np.vstack((original, new_row))

print(with_new_row)

with_new_row = np.vstack((new_row, original))
print(with_new_row)

## V STACK ALLWAYS ADDED ROWWWWWWWWW
# new_col = np.array([[7], [8]])
# print(new_col.shape)
new_column = np.arange(7,9).reshape((2,1))

with_new_col = np.hstack((original, new_column)) ## adding new column

print(with_new_col)

[[1 2]
 [3 4]
 [5 6]]
[[5 6]
 [1 2]
 [3 4]]
[[1 2 7]
 [3 4 8]]
